@hostname=localhost
@port=8000
@url=http://{{hostname}}:{{port}}


###
GET {{url}}/poke-api/web-client?pokeName=Dragonite HTTP/1.1


###
GET {{url}}/poke-api/web-client/tiny?pokeName=Dratini HTTP/1.1
