version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlconf.cnf:/etc/mysql/conf.d/custom.cnf
      - ~/dev/mysqldata-spring:/var/lib/mysql
    networks:
      - database-network

networks:
  database-network:
